name: Check build/run/tests

on:
  push:
    branches: [main]
  pull_request:
      # as by default
      types: [opened, synchronize, reopened]

jobs:
  build:
    name: Deploying
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checking out
      uses: actions/checkout@v4
    - name: Using rpi4 workspace
      using: ./rpi4/.github/workflows/main.yml
      
